name = "BAT"
uuid = "c0cd4b16-88b7-57fa-983b-ab80aecada7e"
version = "3.0.0-DEV"

[deps]
AffineMaps = "2c83c9a8-abf5-4329-a0d7-deffaf474661"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
AutoDiffOperators = "6e1301d5-4f4d-4fb5-9679-7191e22f0e0e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChangesOfVariables = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
EmpiricalDistributions = "0bbb1fad-0f24-45fe-94a4-415852c5cc3b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ForwardDiffPullbacks = "450a3b6d-2448-4ee1-8e34-e4eb8713b605"
FunctionChains = "8e6b2b91-af83-483e-ba35-d00930e4cf9b"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
HeterogeneousComputing = "2182be2a-124f-4a91-8389-f06db5907a21"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
IrrationalConstants = "92d709cd-6900-40b7-9082-c6be49f344b6"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MeasureBase = "fa1605e6-acd5-459c-a1e6-7e635759db14"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
NLSolversBase = "d41bc354-129a-5804-8e4c-c37616107c6c"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
ParallelProcessingTools = "8e8a01fc-6193-5ca1-a2f1-20776dae4199"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Random123 = "74087812-796a-5b5d-8853-05524746bad3"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
ValueShapes = "136a8f8c-c49b-4edb-8b98-f3d64d48be8f"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[weakdeps]
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
NestedSamplers = "41ceaf6f-1696-4a54-9b49-2e7a9ec3782e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
UltraNest = "6822f173-b0be-4018-9ee2-28bf56348d09"

[extensions]
BATAdvancedHMCExt = "AdvancedHMC"
BATCubaExt = "Cuba"
BATFoldsExt = ["Folds", "Transducers"]
BATHDF5Ext = "HDF5"
BATNestedSamplersExt = "NestedSamplers"
BATPlotsExt = "Plots"
BATUltraNestExt = "UltraNest"

[compat]
AffineMaps = "0.2.3"
AdvancedHMC = "0.3, 0.4"
ArgCheck = "1, 2.0"
ArraysOfArrays = "0.4, 0.5, 0.6"
AutoDiffOperators = "0.1"
ChainRulesCore = "0.9.44, 0.10, 1"
ChangesOfVariables = "0.1.1"
Clustering = "0.13, 0.14, 0.15"
Colors = "0.9,0.10,0.11, 0.12"
Cuba = "2"
DensityInterface = "0.4"
DiffResults = "1"
Distributions = "0.25"
DistributionsAD = "0.5, 0.6"
DocStringExtensions = "0.8, 0.9"
DoubleFloats = "0.9, 1"
ElasticArrays = "1.2.3"
EmpiricalDistributions = "0.2, 0.3.1"
FFTW = "1"
FillArrays = "0.7 - 1.0.0, 1.1.1"
FiniteDiff = "2.8"
Folds = "0.2"
ForwardDiff = "0.10"
ForwardDiffPullbacks = "0.1.1, 0.2"
FunctionChains = "0.1.4"
Functors = "0.2, 0.3, 0.4"
HDF5 = "0.15, 0.16"
HeterogeneousComputing = "0.2"
HypothesisTests = "0.10, 0.11"
IntervalSets = "0.5, 0.6, 0.7"
InverseFunctions = "0.1"
IrrationalConstants = "0.1, 0.2"
KernelDensity = "0.5, 0.6"
LaTeXStrings = "1"
MacroTools = "0.5"
MeasureBase = "0.12, 0.13, 0.14"
Measurements = "2"
NLSolversBase = "7"
NamedArrays = "0.9"
NestedSamplers = "0.8"
Optim = "0.19,0.20, 0.21, 0.22, 1"
PDMats = "0.9, 0.10, 0.11"
ParallelProcessingTools = "0.4"
Parameters = "0.12"
Plots = "1"
PositiveFactorizations = "0.2"
PrettyTables = "1, 2"
Random123 = "1.2"
RecipesBase = "0.7, 0.8, 1.0"
Requires = "0.5, 1"
Sobol = "1.4"
StableRNGs = "1"
StaticArrays = "0.12, 1.0"
StatsBase = "0.32, 0.33, 0.34"
StatsFuns = "1"
StructArrays = "0.4, 0.5, 0.6"
Tables = "0.2, 1.0"
Transducers = "0.4"
TypedTables = "1.2"
UltraNest = "0.1"
ValueShapes = "0.10.1"
ZygoteRules = "0.2"
julia = "1.6"

[extras]
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
NestedSamplers = "41ceaf6f-1696-4a54-9b49-2e7a9ec3782e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
UltraNest = "6822f173-b0be-4018-9ee2-28bf56348d09"
