name = "BAT"
uuid = "c0cd4b16-88b7-57fa-983b-ab80aecada7e"
version = "2.0.0-DEV"

[deps]
AdaptiveRejectionSampling = "c75e803d-635f-53bd-ab7d-544e482d8c75"
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
CPUTime = "a9c8d775-2e2e-55fc-8582-045d282d599e"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
EmpiricalDistributions = "0bbb1fad-0f24-45fe-94a4-415852c5cc3b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
NLSolversBase = "d41bc354-129a-5804-8e4c-c37616107c6c"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
ParallelProcessingTools = "8e8a01fc-6193-5ca1-a2f1-20776dae4199"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Random123 = "74087812-796a-5b5d-8853-05524746bad3"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
ValueShapes = "136a8f8c-c49b-4edb-8b98-f3d64d48be8f"

[compat]
AdaptiveRejectionSampling = "0.1.1"
AdvancedHMC = "0.2"
ArgCheck = "1, 2.0"
ArraysOfArrays = "0.4, 0.5"
Bijectors = "0.7, 0.8"
CPUTime = "1.0"
Clustering = "0.13, 0.14"
Colors = "0.9,0.10,0.11, 0.12"
DataStructures = "0.17"
DiffResults = "1"
Distributions = "0.21.10, 0.22, 0.23"
DistributionsAD = "0.5, 0.6"
DoubleFloats = "0.9, 1"
ElasticArrays = "1.2.3"
EmpiricalDistributions = "0.1"
FFTW = "1"
FillArrays = "0.7,0.8, 0.9"
ForwardDiff = "0.10"
HypothesisTests = "0.10"
IntervalSets = "0.5"
KernelDensity = "0.5, 0.6"
LaTeXStrings = "1"
Measurements = "2"
NLSolversBase = "7"
NamedArrays = "0.9"
Optim = "0.19,0.20, 0.21, 0.22"
PDMats = "0.9, 0.10"
ParallelProcessingTools = "0.4"
Parameters = "0.12"
PositiveFactorizations = "0.2"
ProgressMeter = "1"
QuadGK = "2"
Random123 = "1.2"
RecipesBase = "0.7, 0.8, 1.0"
Requires = "0.5, 1"
Sobol = "1.4"
SpecialFunctions = "0.10"
StatsBase = "0.32, 0.33"
StructArrays = "0.4"
Tables = "0.2, 1.0"
TypedTables = "1.2"
ValueShapes = "0.6.10"
julia = "1.3"

[extras]
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Cuba", "HDF5", "StableRNGs", "Test"]
